version: '3'
services:
    postgres:
        container_name: groupchat-pg
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: skilvul-groupchat
